version: "3"
services:
    supremyum_db:
        image: "mariadb:10"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=syspass
        ports:
            - "3306:3306"
    myadmin:
        image: "phpmyadmin/phpmyadmin"
        links:
            - "supremyum_db:db"
        ports:
            - "8080:80"
    supremyum:
        build: .
        links:
            - "supremyum_db:supremyum_db"
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html/
        networks:
            - default